name: pr-check

on:
  pull_request:
    types:
      # default types
      - opened
      - reopened
      - synchronize
      # run when PR title or body changes
      - edited
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    # Give GITHUB_TOKEN write permission
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Check that PR title follows conventional commits using commitlint using regex
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "Your PR title is '$TITLE'"

          regex="(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z[[:space:]]+\))?:[[:space:]].+"

          if [[ $TITLE =~ $regex ]]; then
            echo "PR title follows conventional commits"
          else
            echo "PR title does not follow conventional commits format"
            echo "Prefix your PR title with a descriptor such as 'feat:' and then summarize your change"
            echo "See the following link for more information: https://www.conventionalcommits.org/en/v1.0.0/"
            exit 1
          fi
